[versions]
kotlin = "2.3.0"
kotlinx-serialization = "1.10.0-RC"
vineflower = "1.11.2"

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
